"""Models module"""
from .ngsi_entities import (
    NGSIEntity,
    TouristProfile,
    PointOfInterest,
    Museum,
    Beach,
    Event,
    TouristTrip,
    SocialMatch,
    Alert,
    ConsumptionBehavior,
    TouristDestination,
    Device,
)
from .schemas import (
    POISchema,
    MuseumSchema,
    BeachSchema,
    EventSchema,
    TouristProfileSchema,
    TouristTripSchema,
    RecommendationSchema,
    SocialMatchSchema,
    AlertSchema,
    HealthSchema,
)

__all__ = [
    "NGSIEntity",
    "TouristProfile",
    "PointOfInterest",
    "Museum",
    "Beach",
    "Event",
    "TouristTrip",
    "SocialMatch",
    "Alert",
    "ConsumptionBehavior",
    "TouristDestination",
    "Device",
    "POISchema",
    "MuseumSchema",
    "BeachSchema",
    "EventSchema",
    "TouristProfileSchema",
    "TouristTripSchema",
    "RecommendationSchema",
    "SocialMatchSchema",
    "AlertSchema",
    "HealthSchema",
]
